/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDiceRoller__factory } from "./IDiceRoller__factory";
export { IGameItems__factory } from "./IGameItems__factory";
