/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Battle } from "./Battle";
export type { DiceRoller } from "./DiceRoller";
export type { GameItems } from "./GameItems";
export type { TestDiceRoller } from "./TestDiceRoller";
