const items = [
  {
    id: 0,
    tier: 0,
    name: 'Rock',
    description: 'A powerful rock is one that can be thrown and never stop bouncing.',
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/rock.mp4',
    beats: [2,3,5,7,8],
    playOffs: [6],
    tokenURI: '',
  },
  {
    id: 1,
    tier: 0,
    name: 'Paper',
    description: "I hold this paper in my hand, but it's not heavy, not like my skin. It's light, and I can see my reflection in it.",
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/paper.mp4',
    beats: [0,4,8,10],
    playOffs: [5,7,9],
    tokenURI: '',
  },
  {
    id: 2,
    tier: 0,
    name: 'Scissors',
    description: 'A pair of scissors is a tool with a sharpened blade at a 90 degree angle, on either end of a piece of metal that is usually straight, but can also be curved.',
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/scissors.mp4',
    beats: [1,3,7,9],
    playOffs: [4],
    tokenURI: '',
  },
  {
    id: 3,
    tier: 0,
    name: 'Lizard',
    description: 'The small lizard crawls around quickly, stopping to take a big breath every few seconds.',
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/lizard.mp4',
    beats: [1,4,9],
    playOffs: [5,8,10],
    tokenURI: '',
  },
  {
    id: 4,
    tier: 0,
    name: 'Spock',
    description: 'The hand gesture is the Vulcan peace salute, which consists of raising one hand with the palm open and facing outward, while the fingers of the other hand are squeezed together in a fist.',
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/spock.mp4',
    beats: [0,5,6,9],
    playOffs: [2],
    tokenURI: '',
  },
  {
    id: 5,
    tier: 1,
    name: 'Mirror',
    description: "Every time you look at the 'spooky' mirror, it looks just the same way.",
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/mirror.mp4',
    beats: [2,6,8,10],
    playOffs: [1,3],
    tokenURI: '',
  },
  {
    id: 6,
    tier: 1,
    name: 'Torch',
    description: "The existential torch is a gentle light illuminating the way to a brighter future.",
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/torch.mp4',
    beats: [1,3,7,9],
    playOffs: [0],
    tokenURI: '',
  },
  {
    id: 7,
    tier: 1,
    name: 'Chili Pepper',
    description: "In order to attain this heat level, it may have to be dried and crushed into a powder, the most extreme pepper would be The Carolina Reaper.",
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/pepper.mp4',
    beats: [2,4,9],
    combined: [],
    tokenURI: '',
  },
  {
    id: 8,
    name: 'Ice Sculpture',
    description: "This beautiful ice sculpture of a polar bear is the product of a talented ice sculptor. The sculpture makes for a dramatic scene.",
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/iceSculpture.mp4',
    beats: [2,4,6,7,10],
    playOffs: [3,9],
    tokenURI: '',
  },
  {
    id: 9,
    tier: 2,
    name: 'Heart',
    description: "Every time Mylilius lays on the console, he closes his eyes and falls asleep.",
    image: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/heart.gif',
    animation: '',
    beats: [0,3,5,11],
    playOffs: [1,8],
    tokenURI: '',
  },
  {
    id: 10,
    tier: 2,
    name: 'Mask',
    description: "Larva Maiorum is a mask worn by the people of southern Italy in the province of El Oro.",
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/mask.mp4',
    beats: [1,4,6,9],
    playOffs: [3],
    tokenURI: '',
  },
  {
    id: 11,
    tier: 2,
    name: 'Ruby',
    description: "A Ruby is a medium of exchange because it is used as money for goods and services.",
    image: '',
    animation: 'ipfs://bafybeiaug4zos5ium3qagglul6vdwka5sncmh4i4ez74opearfw3lmrcxe/ruby.mp4',
    beats: [0,5,6,8,9],
    playOffs: [],
    tokenURI: '',
  },
]

export default items;
